name: Sync to Deployment Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Deployment Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOYMENT_PAT }}
        with:
          source-directory: '.'
          destination-github-username: 'emmanuel2406'
          destination-repository-name: 'scrap-slides-deployment'
          user-email: 'github-actions[bot]@users.noreply.github.com'
          target-branch: 'main'
    
